# Generated by Django 6.0 on 2025-12-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_deleted_by_message_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_everyone',
            field=models.BooleanField(default=False),
        ),
    ]
