# Generated by Django 6.0 on 2025-12-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='call_duration',
            field=models.IntegerField(blank=True, help_text='Call duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='call_status',
            field=models.CharField(blank=True, choices=[('missed', 'Missed'), ('answered', 'Answered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('call', 'Call')], default='text', max_length=10),
        ),
    ]
